// macOS URL-scheme registrar.
//
// macOS does NOT deliver custom-scheme URLs on argv — it launches the registered
// .app bundle and sends the URL via an Apple Event (GURL). The no-compiler way to
// receive that is an AppleScript applet with an `on open location` handler, whose
// Info.plist declares the scheme in CFBundleURLTypes, registered with Launch Services.
//
// TCC note: an app launched by Launch Services has NO access to ~/Documents, ~/Desktop,
// etc. Our checkout lives under ~/Documents, so the handler cannot run the code in place.
// So `register` copies a self-contained runtime SNAPSHOT (src + fixtures + .env) into the
// bundle's Contents/Resources/sim (~/Applications is not TCC-protected) — exactly how a
// real desktop app ships. Consequence: re-run `register` after editing code or .env.

import { mkdtemp, writeFile, rm, mkdir, readFile, cp } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir, homedir } from 'node:os';
import { join } from 'node:path';

import { run, runOrThrow, which } from './exec.js';

const LSREGISTER =
  '/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister';

// --- path helpers ---------------------------------------------------------

function sanitizeForBundleId(scheme) {
  // Bundle ids allow alphanumerics, hyphens and dots. Strip anything else.
  const cleaned = String(scheme).replace(/[^A-Za-z0-9-]/g, '');
  return cleaned || 'scheme';
}

function appPaths(scheme) {
  const safe = sanitizeForBundleId(scheme);
  const appDir = join(homedir(), 'Applications');
  const appPath = join(appDir, `scanpro-sim-${safe}.app`);
  const resourcesSim = join(appPath, 'Contents', 'Resources', 'sim'); // bundled runtime snapshot
  return {
    appDir,
    appPath,
    resourcesSim,
    plist: join(appPath, 'Contents', 'Info.plist'),
    bundleId: `com.sprintray.scanprosim.${safe}`,
    // Logs live outside both ~/Documents (TCC) and the bundle (wiped on re-register).
    logFile: join(homedir(), 'Library', 'Logs', 'scanpro-sim', `${safe}.log`),
  };
}

/** Escape a string for embedding inside an AppleScript double-quoted literal. */
function asLiteral(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

// --- AppleScript applet source -------------------------------------------

function appleScriptSource({ nodeBin, bundledSim, bundledIndex, bundledEnv, logFile, headless }) {
  const LOG = asLiteral(logFile);
  const LOGDIR = asLiteral(join(logFile, '..'));

  // The shell command is assembled with AppleScript string concatenation so the URL
  // and every baked path stay OUTSIDE the shell string and are `quoted form`-safe.
  const buildCmd =
    `"cd " & quoted form of ${asLiteral(bundledSim)} & " && " & ` +
    `quoted form of ${asLiteral(nodeBin)} & " --env-file=" & quoted form of ${asLiteral(bundledEnv)} & " " & ` +
    `quoted form of ${asLiteral(bundledIndex)} & " " & argPart`;

  // node runs via `do shell script`, which needs NO Automation permission. The Terminal
  // window is a nice-to-have for live viewing; if that AppleEvent is blocked (TCC), we
  // fall back to headless so the scan STILL runs instead of silently doing nothing.
  const dispatch = headless
    ? `		do shell script (${buildCmd} & " >> " & quoted form of ${LOG} & " 2>&1 &")`
    : `		set headlessCmd to (${buildCmd} & " >> " & quoted form of ${LOG} & " 2>&1 &")\n` +
      `		set termCmd to (${buildCmd} & " 2>&1 | /usr/bin/tee -a " & quoted form of ${LOG})\n` +
      `		try\n` +
      `			tell application "Terminal"\n` +
      `				activate\n` +
      `				do script termCmd\n` +
      `			end tell\n` +
      `		on error\n` +
      `			do shell script "echo '[handler] Terminal blocked (grant Automation, or use --headless) — running headless; output follows' >> " & quoted form of ${LOG}\n` +
      `			do shell script headlessCmd\n` +
      `			try\n` +
      `				display notification "Ran headless — see the log for scan output." with title "ScanPro Simulator"\n` +
      `			end try\n` +
      `		end try`;

  return `-- Generated by scanpro-simulator \`register\`. Runs a snapshot bundled in Contents/Resources/sim.
-- Re-run register after editing code or .env.
on open location this_URL
	my launchSim(this_URL)
end open location

on run
	my launchSim(missing value)
end run

on launchSim(this_URL)
	do shell script "/bin/mkdir -p " & quoted form of ${LOGDIR}
	do shell script "echo '[handler] fired' >> " & quoted form of ${LOG}
	if this_URL is missing value then
		set argPart to "--help"
	else
		set argPart to quoted form of this_URL
	end if
${dispatch}
end launchSim
`;
}

// --- public API -----------------------------------------------------------

/**
 * Register (or re-register) the applet as the macOS handler for `scheme`.
 * @param {{ scheme: string, nodeBin: string, simDir: string, envFile: string, headless?: boolean }} opts
 * @returns {Promise<{appPath: string, handler: string|null, isDefault: boolean|null, logFile: string, bundledEnv: boolean}>}
 */
export async function register(opts) {
  const { scheme, nodeBin, simDir, envFile, headless } = opts;

  if (!(await which('osacompile'))) {
    throw new Error('osacompile not found — required to build the URL-handler app on macOS');
  }

  const { appDir, appPath, resourcesSim, plist, bundleId, logFile } = appPaths(scheme);
  const bundledIndex = join(resourcesSim, 'src', 'index.js');
  const bundledEnv = join(resourcesSim, '.env');
  await mkdir(appDir, { recursive: true });

  // 1) Compile the applet from a temp source file (baked paths point into the bundle).
  const tmp = await mkdtemp(join(tmpdir(), 'scanpro-scheme-'));
  const scriptFile = join(tmp, 'handler.applescript');
  try {
    await writeFile(
      scriptFile,
      appleScriptSource({ nodeBin, bundledSim: resourcesSim, bundledIndex, bundledEnv, logFile, headless })
    );
    await rm(appPath, { recursive: true, force: true });
    await runOrThrow('osacompile', ['-o', appPath, scriptFile]);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }

  // 2) Copy a self-contained runtime snapshot into the bundle (TCC-safe location).
  await mkdir(resourcesSim, { recursive: true });
  await cp(join(simDir, 'src'), join(resourcesSim, 'src'), { recursive: true });
  await cp(join(simDir, 'fixtures'), join(resourcesSim, 'fixtures'), { recursive: true });
  const bundledEnvExists = existsSync(envFile);
  if (bundledEnvExists) await cp(envFile, bundledEnv);

  // 3) Patch Info.plist: declare the scheme, pin a stable bundle id, hide from the Dock.
  await runOrThrow('plutil', ['-replace', 'CFBundleIdentifier', '-string', bundleId, plist]);
  await runOrThrow('plutil', ['-replace', 'CFBundleName', '-string', `ScanPro Simulator (${scheme})`, plist]);
  await runOrThrow('plutil', ['-replace', 'LSUIElement', '-bool', 'true', plist]);
  const urlTypes = JSON.stringify([{ CFBundleURLName: bundleId, CFBundleURLSchemes: [scheme] }]);
  await runOrThrow('plutil', ['-replace', 'CFBundleURLTypes', '-json', urlTypes, plist]);

  // 4) Register with Launch Services.
  await runOrThrow(LSREGISTER, ['-f', appPath]);

  // 5) Best-effort confirmation of the actual default handler.
  const handler = await defaultHandler(scheme);
  const isDefault = handler == null ? null : handler === appPath;
  return { appPath, handler, isDefault, logFile, bundledEnv: bundledEnvExists };
}

/**
 * Remove our applet for `scheme` and unregister it from Launch Services.
 * @returns {Promise<{appPath: string, existed: boolean}>}
 */
export async function unregister(scheme) {
  const { appPath } = appPaths(scheme);
  const existed = existsSync(appPath);
  if (existed) {
    await run(LSREGISTER, ['-u', appPath]); // best-effort
    await rm(appPath, { recursive: true, force: true });
  }
  return { appPath, existed };
}

/**
 * Report registration state for `scheme`.
 * @returns {Promise<{appPath: string, appExists: boolean, declaredSchemes: string[]|null, handler: string|null, isDefault: boolean|null}>}
 */
export async function status(scheme) {
  const { appPath, plist } = appPaths(scheme);
  const appExists = existsSync(appPath);

  let declaredSchemes = null;
  if (appExists) {
    try {
      const raw = await readFile(plist, 'utf8');
      // Info.plist is XML; pull scheme strings out of CFBundleURLSchemes without a plist parser.
      const m = raw.match(/<key>CFBundleURLSchemes<\/key>\s*<array>([\s\S]*?)<\/array>/);
      if (m) declaredSchemes = [...m[1].matchAll(/<string>([^<]*)<\/string>/g)].map((x) => x[1]);
    } catch {
      declaredSchemes = null;
    }
  }

  const handler = await defaultHandler(scheme);
  const isDefault = handler == null ? null : handler === appPath;
  return { appPath, appExists, declaredSchemes, handler, isDefault };
}

/**
 * Ask Launch Services which app is the default handler for `scheme`, via a Swift
 * one-liner (NSWorkspace). Returns the app path, or null if swift is unavailable
 * or no handler is registered.
 */
async function defaultHandler(scheme) {
  if (!(await which('swift'))) return null;
  const swiftSrc = `import AppKit
let s = CommandLine.arguments[1]
guard let u = URL(string: "\\(s)://probe") else { exit(2) }
if let app = NSWorkspace.shared.urlForApplication(toOpen: u) { print(app.path) }
`;
  try {
    const r = await run('swift', ['-', scheme], { input: swiftSrc });
    const out = r.stdout.trim();
    return r.code === 0 && out ? out : null;
  } catch {
    return null;
  }
}
